"""Official Python SDK for the Nexus Exchange API (experimental).

See the README for the current support table. Quick start::

    from nexus_exchange import Client

    with Client() as client:
        for market in client.fetch_markets():
            print(market.market_id)
"""

from __future__ import annotations

from .auth import (
    SIGN_IN_MESSAGE,
    AgentRegistered,
    AgentRegistration,
    EthSigner,
    LoginRequest,
    LoginResponse,
)
from .client import (
    CLOSED_POSITIONS_LIMIT_MAX,
    DEFAULT_API_VERSION,
    DEFAULT_USER_AGENT,
    EQUITY_HISTORY_LIMIT_MAX,
    FILLS_LIMIT_MAX,
    ORDER_HISTORY_LIMIT_MAX,
    PORTFOLIO_LIMIT_MAX,
    TRADES_LIMIT_MAX,
    Client,
    __version__,
)
from .errors import (
    JURISDICTION_CODES,
    ApiError,
    AuthError,
    DecodeError,
    MissingCredentialsError,
    NexusExchangeError,
    PaginationError,
    RestrictedJurisdictionError,
    TransportError,
)
from .networks import (
    Funds,
    Network,
    NetworkConfig,
    SigningDomain,
)
from .pagination import Page, iter_items, iter_pages
from .types import (
    AccountFees,
    AccountPortfolioSummary,
    AccountState,
    AccountSummary,
    AdlClosure,
    AdlEvent,
    AgentInfo,
    AmendOrder,
    ApiKeyInfo,
    BatchOrderResult,
    BridgeAsset,
    BridgeAssetsResponse,
    BridgeChainAssets,
    BridgeDeposit,
    BridgeDepositAddress,
    CancelOnDisconnectStatus,
    ClosedPosition,
    CreditResult,
    DepositResult,
    EquityPoint,
    Fill,
    FundingSample,
    HealthStatus,
    LeverageUpdate,
    MarginAdjustment,
    Market,
    MarketStatus,
    MarketSummary,
    MarkPrice,
    Ohlcv,
    Order,
    OrderBook,
    OrderHistoryEntry,
    OrderRequest,
    OrderResponse,
    PortfolioHistory,
    PortfolioPoint,
    PortfolioWindow,
    Position,
    PriceLevel,
    RateLimitStatus,
    Ticker,
    TierOverride,
    Trade,
    Withdrawal,
    WsToken,
)

__all__ = [
    "BridgeAsset",
    "BridgeAssetsResponse",
    "BridgeChainAssets",
    "BridgeDeposit",
    "BridgeDepositAddress",
    "Client",
    "Network",
    "NetworkConfig",
    "Funds",
    "SigningDomain",
    "Market",
    "MarketSummary",
    "MarketStatus",
    "Ticker",
    "OrderBook",
    "PriceLevel",
    "Trade",
    "Ohlcv",
    "FundingSample",
    "MarkPrice",
    "AdlEvent",
    "AdlClosure",
    "HealthStatus",
    "EthSigner",
    "LoginRequest",
    "AgentRegistration",
    "LoginResponse",
    "AgentRegistered",
    "SIGN_IN_MESSAGE",
    "AccountSummary",
    "AccountPortfolioSummary",
    "AccountState",
    "AccountFees",
    "PortfolioHistory",
    "PortfolioPoint",
    "PortfolioWindow",
    "Position",
    "ClosedPosition",
    "EquityPoint",
    "Fill",
    "Order",
    "OrderHistoryEntry",
    "OrderRequest",
    "OrderResponse",
    "AmendOrder",
    "MarginAdjustment",
    "LeverageUpdate",
    "BatchOrderResult",
    "DepositResult",
    "CreditResult",
    "Withdrawal",
    "RateLimitStatus",
    "CancelOnDisconnectStatus",
    "ApiKeyInfo",
    "AgentInfo",
    "TierOverride",
    "WsToken",
    "NexusExchangeError",
    "ApiError",
    "AuthError",
    "TransportError",
    "MissingCredentialsError",
    "DecodeError",
    "PaginationError",
    "RestrictedJurisdictionError",
    "JURISDICTION_CODES",
    "Page",
    "iter_pages",
    "iter_items",
    "CLOSED_POSITIONS_LIMIT_MAX",
    "EQUITY_HISTORY_LIMIT_MAX",
    "FILLS_LIMIT_MAX",
    "ORDER_HISTORY_LIMIT_MAX",
    "PORTFOLIO_LIMIT_MAX",
    "TRADES_LIMIT_MAX",
    "DEFAULT_USER_AGENT",
    "DEFAULT_API_VERSION",
    "__version__",
]
