# GENERATED by scripts/gen_async_client.py from src/nexus_exchange/client.py.
# Do not edit by hand: change `Client`, then run `python scripts/gen_async_client.py`.
# tests/test_async_client.py fails while this file is stale.
"""Asynchronous HTTP client for the Nexus Exchange API.

:class:`AsyncClient` is :class:`~nexus_exchange.Client` with awaitable I/O over
``httpx.AsyncClient``. Every method, argument and docstring below is the sync
client's; see ``scripts/gen_async_client.py`` for how it is derived.
"""

from __future__ import annotations

import warnings
from collections.abc import AsyncIterator
from decimal import Decimal, InvalidOperation
from typing import Any
from urllib.parse import quote, urlencode

from ._async_transport import _AsyncTransport
from ._parse import to_dict_list
from .auth import AgentRegistered, AgentRegistration, EthSigner, LoginResponse
from .client import (
    ACCOUNT_FUNDING_LIMIT_MAX,
    CLOSED_POSITIONS_LIMIT_MAX,
    DEPOSITS_LIMIT_MAX,
    EQUITY_HISTORY_LIMIT_MAX,
    FILLS_LIMIT_MAX,
    FUNDING_SAMPLES_LIMIT_MAX,
    ORDER_HISTORY_LIMIT_MAX,
    TRADES_LIMIT_MAX,
    _bearer_token,
    _check_iter_args,
    _page_limit,
    _portfolio_limit,
    _portfolio_window,
    _query,
    _warn_renamed,
)
from .pagination import Page, aiter_items
from .types import (
    AccountFees,
    AccountFunding,
    AccountPortfolioSummary,
    AccountState,
    AccountSummary,
    AdlEvent,
    AgentInfo,
    AmendOrder,
    ApiKeyCreated,
    ApiKeyInfo,
    BatchOrderResult,
    BridgeAssetsResponse,
    BridgeDeposit,
    BridgeDepositAddress,
    CancelOnDisconnectStatus,
    ClosedPosition,
    CreditResult,
    DepositResponse,
    DepositResult,
    EquityPoint,
    FaucetResponse,
    Fill,
    FundingPremiumSample,
    FundingSample,
    FundsEntry,
    MarginAdjustment,
    Market,
    MarketRiskParams,
    MarketStatus,
    MarketSummary,
    MarkPrice,
    Ohlcv,
    Order,
    OrderBook,
    OrderHistoryEntry,
    OrderRequest,
    OrderResponse,
    PortfolioHistory,
    PortfolioWindow,
    Position,
    PreviewResponse,
    RateLimitStatus,
    ServiceHealth,
    StatsSnapshot,
    ThroughputSample,
    Ticker,
    TierOverride,
    Trade,
    Withdrawal,
    WsToken,
)

__all__ = ["AsyncClient"]


class AsyncClient(_AsyncTransport):
    """Async client for the Nexus Exchange REST API.

    The same surface as :class:`~nexus_exchange.Client`: the same constructor
    arguments (``http_client`` takes an ``httpx.AsyncClient``), the same
    methods, the same signing, retry policy and errors. Each method is a
    coroutine, except the ``iter_*`` walkers, which return an async iterator::

        async with AsyncClient() as client:
            markets = await client.fetch_markets()
            async for fill in client.iter_my_trades(limit=500):
                ...

    Retries back off with ``asyncio.sleep``, so they never block the event
    loop. Close with ``async with`` or :meth:`aclose`.

    The method docstrings are copied from :class:`~nexus_exchange.Client`, so
    where one says "generator" read "async iterator", and add the missing
    ``await`` to its examples.
    """

    # -- public market data ----------------------------------------------
    async def fetch_markets(self) -> list[Market]:
        """``GET /markets`` — all tradable markets and their trading rules."""
        data = await self._request("GET", "/markets")
        rows = data if isinstance(data, list) else data.get("markets", [])
        return [Market.from_dict(m) for m in rows]

    async def fetch_markets_summary(self) -> list[MarketSummary]:
        """``GET /markets/summary`` — per-market 24h volume and halt state."""
        data = await self._request("GET", "/markets/summary")
        rows = data if isinstance(data, list) else data.get("markets", [])
        return [MarketSummary.from_dict(m) for m in rows]

    async def fetch_tickers(self) -> dict[str, Ticker]:
        """``GET /tickers`` — tickers for all markets, keyed by market id.

        The envelope is a bare object keyed by market id (spec:
        ``additionalProperties: Ticker``); an empty result is ``{}``.
        """
        data = await self._request("GET", "/tickers")
        if not isinstance(data, dict):
            return {}
        return {mid: Ticker.from_dict(t) for mid, t in data.items()}

    async def fetch_ticker(self, market_id: str) -> Ticker:
        """``GET /markets/{market_id}/ticker`` — latest ticker for one market."""
        data = await self._request("GET", f"/markets/{quote(market_id, safe='')}/ticker")
        return Ticker.from_dict(data if isinstance(data, dict) else {"symbol": market_id})

    async def fetch_order_book(self, market_id: str) -> OrderBook:
        """``GET /markets/{market_id}/orderbook`` — order book snapshot."""
        data = await self._request("GET", f"/markets/{quote(market_id, safe='')}/orderbook")
        return OrderBook.from_dict(data if isinstance(data, dict) else {})

    async def fetch_trades(self, market_id: str, limit: int | None = None) -> list[Trade]:
        """``GET /markets/{market_id}/trades`` — recent public trades (newest first).

        Returns the first page only. ``limit`` bounds it and must fall in
        ``1..1000`` (:data:`TRADES_LIMIT_MAX`); omit it for the server's default
        of 100. For more than one page use :meth:`iter_trades` (every trade) or
        :meth:`fetch_trades_page` (one page plus its cursor).
        """
        return (await self.fetch_trades_page(market_id, limit=limit)).items

    async def fetch_trades_page(
        self,
        market_id: str,
        *,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[Trade]:
        """``GET /markets/{market_id}/trades`` — one page, plus its next cursor.

        The manual-paging form: :attr:`Page.next_cursor` is the value to pass
        back as ``cursor`` for the following page, and is ``None`` on the last
        page. Use this when the cursor must outlive the process (a resumable
        backfill); use :meth:`iter_trades` to just walk everything.
        """
        query = _query(
            limit=_page_limit(limit, TRADES_LIMIT_MAX, "trades"),
            cursor=cursor,
        )
        data, next_cursor = await self._request_page(
            f"/markets/{quote(market_id, safe='')}/trades", query=query
        )
        rows = data if isinstance(data, list) else []
        return Page([Trade.from_dict(t) for t in rows], next_cursor)

    def iter_trades(
        self,
        market_id: str,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[Trade]:
        """Every public trade for ``market_id``, paging by cursor as needed.

        A generator: pages are fetched lazily, one request at a time, so breaking
        out of the loop stops the requests. ``limit`` sets the *page* size (not a
        total), ``cursor`` resumes from a saved position, and ``max_pages`` bounds
        the walk — worth setting on a market with a long trade history, since
        nothing else limits how far back this goes.

        See :mod:`nexus_exchange.pagination` for the termination rules (absent
        ``X-Next-Cursor`` ends the walk; a non-advancing cursor raises
        :class:`~nexus_exchange.PaginationError`).
        """
        _check_iter_args(limit, TRADES_LIMIT_MAX, "trades", max_pages)
        return aiter_items(
            lambda c: self.fetch_trades_page(market_id, limit=limit, cursor=c),
            cursor=cursor,
            max_pages=max_pages,
        )

    async def fetch_ohlcv(
        self,
        market_id: str,
        timeframe: str | None = None,
        limit: int | None = None,
    ) -> list[Ohlcv]:
        """``GET /markets/{market_id}/candles`` — OHLCV candles."""
        query = _query(timeframe=timeframe, limit=limit)
        data = await self._request(
            "GET", f"/markets/{quote(market_id, safe='')}/candles", query=query
        )
        rows = data if isinstance(data, list) else []
        return [Ohlcv.from_row(r) for r in rows]

    async def fetch_funding_rate_history(
        self, market_id: str, limit: int | None = None
    ) -> list[FundingSample]:
        """``GET /markets/{market_id}/funding`` — intra-hour funding-rate history."""
        query = _query(limit=limit)
        data = await self._request(
            "GET", f"/markets/{quote(market_id, safe='')}/funding", query=query
        )
        rows = data if isinstance(data, list) else []
        return [FundingSample.from_dict(s) for s in rows]

    async def fetch_mark_price(self, market_id: str) -> MarkPrice:
        """``GET /markets/{market_id}/mark-price`` — current mark price."""
        data = await self._request("GET", f"/markets/{quote(market_id, safe='')}/mark-price")
        return MarkPrice.from_dict(data if isinstance(data, dict) else {})

    async def fetch_market_status(self, market_id: str) -> MarketStatus:
        """``GET /markets/{market_id}/status`` — lifecycle / halt status."""
        data = await self._request("GET", f"/markets/{quote(market_id, safe='')}/status")
        return MarketStatus.from_dict(data if isinstance(data, dict) else {})

    async def fetch_adl_events(self, market_id: str, limit: int | None = None) -> list[AdlEvent]:
        """``GET /markets/{market_id}/adl-events`` — ADL settlement events (newest first)."""
        query = _query(limit=limit)
        data = await self._request(
            "GET", f"/markets/{quote(market_id, safe='')}/adl-events", query=query
        )
        rows = data if isinstance(data, list) else []
        return [AdlEvent.from_dict(e) for e in rows]

    async def fetch_adl_history(self, address: str, limit: int | None = None) -> list[AdlEvent]:
        """``GET /account/{address}/adl-history`` — ADL events touching an account."""
        query = _query(limit=limit)
        data = await self._request(
            "GET", f"/account/{quote(address, safe='')}/adl-history", query=query
        )
        rows = data if isinstance(data, list) else []
        return [AdlEvent.from_dict(e) for e in rows]

    async def fetch_market_risk_params(self, market_id: str) -> MarketRiskParams:
        """``GET /markets/{market_id}/risk-params`` — margin rates and leverage cap.

        Public. The margin rates are decimal *ratios* (``0.05`` is 5%), not
        percentages.

        Overlaps :meth:`fetch_markets`, which carries the same three values per
        market inside its trading rules. This route is the per-market read, and
        is served by the indexer straight from the engine's market registry — so
        prefer it when you want one market's risk terms without pulling the
        whole market list.

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        if not market_id:
            raise ValueError("market_id is required")
        data = await self._request("GET", f"/markets/{quote(market_id, safe='')}/risk-params")
        return MarketRiskParams.from_dict(data if isinstance(data, dict) else {})

    async def fetch_funding_samples(
        self, market_id: str, limit: int | None = None
    ) -> list[FundingPremiumSample]:
        """``GET /markets/{market_id}/funding-samples`` — premium-index samples.

        Public. Intra-window observations of the premium index, **not** settled
        funding: :meth:`fetch_funding_rate_history` is the settled series, and
        the two are different shapes for a reason (see
        :class:`~nexus_exchange.FundingPremiumSample`).

        ``limit`` defaults to 480 server-side, which is also its maximum
        (:data:`FUNDING_SAMPLES_LIMIT_MAX`) — one page covers the whole retained
        window, so omitting it asks for everything rather than a short page.
        """
        if not market_id:
            raise ValueError("market_id is required")
        limit = _page_limit(limit, FUNDING_SAMPLES_LIMIT_MAX, "funding-samples")
        query = _query(limit=limit)
        data = await self._request(
            "GET",
            f"/markets/{quote(market_id, safe='')}/funding-samples",
            query=query,
        )
        return [FundingPremiumSample.from_dict(s) for s in (data if isinstance(data, list) else [])]

    async def fetch_stats(self) -> StatsSnapshot:
        """``GET /stats`` — aggregate venue statistics. Public.

        Includes the rolling unique-trader counts (DAU/WAU/MAU) that the bare
        snapshot schema marks as present on this route.
        """
        data = await self._request("GET", "/stats")
        return StatsSnapshot.from_dict(data if isinstance(data, dict) else {})

    async def fetch_stats_history(self) -> list[ThroughputSample]:
        """``GET /stats/history`` — venue throughput ring buffer. Public.

        1s cadence, capped at 3600 points. Note each sample's ``timestamp`` is
        Unix **seconds**, unlike every other timestamp on this surface — see
        :class:`~nexus_exchange.ThroughputSample`.
        """
        data = await self._request("GET", "/stats/history")
        return [ThroughputSample.from_dict(s) for s in (data if isinstance(data, list) else [])]

    async def fetch_status(self) -> ServiceHealth:
        """``GET /status`` — aggregate service health. Public.

        Branch on ``status`` (worst-of across components); the per-component
        ``services`` detail is informational and free to change shape.

        This is the contract's health operation. It replaced the legacy
        gateway's ``GET /health`` probe, which was never a contract operation
        and was dropped upstream in v0.7.1 (ENG-8618).

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        data = await self._request("GET", "/status")
        return ServiceHealth.from_dict(data if isinstance(data, dict) else {})

    # -- wallet-signed auth ----------------------------------------------
    async def login(self, signer: EthSigner) -> LoginResponse:
        """``POST /auth/login`` — EIP-191 session login.

        Signs the fixed login message with ``signer`` and posts the result.
        Unauthenticated: the EIP-191 signature in the body is the credential.
        Returns the session token (treat as secret) and the recovered address.
        """
        body = signer.sign_in().to_dict()
        data = await self._request("POST", "/auth/login", body=body)
        return LoginResponse.from_dict(data if isinstance(data, dict) else {})

    async def register_agent(self, registration: AgentRegistration) -> AgentRegistered:
        """``POST /agents/register`` — EIP-712 agent-key registration.

        Takes a pre-signed body from
        :meth:`EthSigner.register_agent <nexus_exchange.EthSigner.register_agent>`.
        Unauthenticated: the EIP-712 signature in the body is the credential.
        """
        data = await self._request("POST", "/agents/register", body=registration.to_dict())
        return AgentRegistered.from_dict(data if isinstance(data, dict) else {})

    # -- account (signed reads) ------------------------------------------
    async def fetch_balance(self) -> AccountSummary:
        """``GET /account`` — balance and collateral summary. Requires credentials."""
        data = await self._request("GET", "/account", signed=True)
        return AccountSummary.from_dict(data if isinstance(data, dict) else {})

    async def fetch_positions(self) -> list[Position]:
        """``GET /positions`` — open positions. Requires credentials.

        As of API spec v0.7.2 each :class:`Position` also carries per-position
        risk detail (notional value, ROE, margin used, max leverage, funding
        paid). Those fields are ``None`` when the server cannot derive them,
        with the reason in the companion ``*_error`` — see :class:`Position`.

        A non-object in the list raises :class:`~nexus_exchange.DecodeError`
        rather than being skipped, so this list, ``fetch_balance().positions``
        and ``fetch_account_state().positions`` all fail the same way instead of
        one of them silently understating exposure.
        """
        data = await self._request("GET", "/positions", signed=True)
        return [Position.from_dict(p) for p in to_dict_list(data, "positions", required=False)]

    async def fetch_positions_history(self, limit: int | None = None) -> list[ClosedPosition]:
        """``GET /positions/closed`` — closed positions, newest first.

        The realized counterpart of :meth:`fetch_positions`. Requires
        credentials.

        Returns the first page only. ``limit`` bounds it and must fall in
        ``1..200`` (:data:`CLOSED_POSITIONS_LIMIT_MAX` — the smallest of the
        paginated maxima); omit it for the server's default of 100. For the whole
        history use :meth:`iter_positions_history`, or
        :meth:`fetch_positions_history_page` for one page plus its cursor.
        """
        return (await self.fetch_positions_history_page(limit=limit)).items

    async def fetch_positions_history_page(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[ClosedPosition]:
        """``GET /positions/closed`` — one page of closed positions, plus its cursor.

        The manual-paging form; see :meth:`fetch_trades_page`. Requires
        credentials.
        """
        query = _query(
            limit=_page_limit(limit, CLOSED_POSITIONS_LIMIT_MAX, "positions/closed"),
            cursor=cursor,
        )
        data, next_cursor = await self._request_page("/positions/closed", query=query, signed=True)
        rows = data if isinstance(data, list) else []
        return Page([ClosedPosition.from_dict(p) for p in rows], next_cursor)

    def iter_positions_history(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[ClosedPosition]:
        """Every closed position on the account, paging by cursor as needed.

        A generator; each page costs one signed request, issued lazily. ``limit``
        sets the page size (max 200 here, so a long history takes proportionally
        more pages than ``/fills`` would), ``cursor`` resumes from a saved
        position, and ``max_pages`` bounds the walk.

        See :mod:`nexus_exchange.pagination` for the termination rules.
        """
        _check_iter_args(limit, CLOSED_POSITIONS_LIMIT_MAX, "positions/closed", max_pages)
        return aiter_items(
            lambda c: self.fetch_positions_history_page(limit=limit, cursor=c),
            cursor=cursor,
            max_pages=max_pages,
        )

    async def fetch_account_state(self) -> AccountState:
        """``GET /account/state`` — consolidated account snapshot. Requires credentials.

        One signed call for the portfolio summary aggregates *and* every open
        position, replacing a ``/account/summary`` + ``/positions`` pair. Both
        halves come from one coherent server-side read, so
        ``state.summary.open_positions_count == len(state.positions)``.

        ``state.summary.withdrawable`` is the authoritative wallet-withdrawable
        balance. This endpoint **fails closed**: when the engine-authoritative
        margin view is unavailable it returns HTTP 502
        (``authoritative_margin_unavailable``, raised as :class:`ApiError`)
        rather than a locally-estimated figure. That is transient — retry after
        a short delay rather than falling back to a self-computed number.

        Use :meth:`fetch_account_summary` when only the aggregates are needed —
        it returns the same ``summary`` without the position list.
        """
        data = await self._request("GET", "/account/state", signed=True)
        return AccountState.from_dict(data if isinstance(data, dict) else {})

    async def fetch_account_summary(self) -> AccountPortfolioSummary:
        """``GET /account/summary`` — aggregate portfolio view. Requires credentials.

        The summary-only half of :meth:`fetch_account_state`: equity, PnL,
        volume, margin and ``withdrawable``, without the position list. Prefer it
        when the aggregates are all you need; prefer
        :meth:`fetch_account_state` when you also want positions, since that is
        one coherent read rather than two calls that can straddle a fill.

        Distinct from :meth:`fetch_balance` (``GET /account``), which is the
        balance/collateral view — see :class:`AccountPortfolioSummary` versus
        :class:`AccountSummary`.

        Fails closed on the same HTTP 502 (``authoritative_margin_unavailable``,
        raised as :class:`ApiError`) as :meth:`fetch_account_state`, for the same
        reason: no locally-estimated ``withdrawable`` is ever substituted.
        """
        data = await self._request("GET", "/account/summary", signed=True)
        return AccountPortfolioSummary.from_dict(data if isinstance(data, dict) else {})

    async def fetch_trading_fees(self) -> AccountFees:
        """``GET /account/fees`` — the account's effective fee schedule.

        Requires credentials; the account is taken from the signing credentials,
        not a parameter. Returns the forward-looking *schedule* rate (maker /
        taker bps, fee tier, rolling 30-day volume, active discounts), not a
        realized per-fill average. ``maker_fee_bps`` may be negative — a rebate
        paid to the maker. See :class:`AccountFees` for the ``schedule``
        scoping caveat and the ``volume_30d_estimated`` flag.
        """
        data = await self._request("GET", "/account/fees", signed=True)
        return AccountFees.from_dict(data if isinstance(data, dict) else {})

    async def fetch_portfolio_history(
        self,
        window: PortfolioWindow | str | None = None,
        limit: int | None = None,
    ) -> PortfolioHistory:
        """``GET /account/portfolio-history`` — portfolio time series.

        Requires credentials. Returns equity, cumulative trading PnL, and
        cumulative traded volume over ``window``, downsampled at a fixed
        per-window cadence, ``points`` **oldest first**.

        ``window`` takes a :class:`PortfolioWindow` member or its string value
        (``"day"`` / ``"week"`` / ``"month"`` / ``"all"``); omit it for the
        server's ``day`` default. ``limit`` caps the returned points and must
        fall in ``1..366``. Both are validated before the request, so a bad
        value raises :class:`ValueError` instead of costing a signed round trip
        (the server would answer ``400 invalid_window``). Each window has its
        own point capacity — ``limit`` above it is capped server-side, so asking
        for more never yields more.

        A malformed *response* raises :class:`~nexus_exchange.DecodeError`
        instead, so caller error and server-payload defects are distinguishable
        by type; every field of this response is spec-``required`` and none is
        defaulted. See :class:`PortfolioHistory`.
        """
        query = _query(
            window=_portfolio_window(window),
            limit=_portfolio_limit(limit),
        )
        data = await self._request("GET", "/account/portfolio-history", query=query, signed=True)
        return PortfolioHistory.from_dict(data if isinstance(data, dict) else {})

    async def fetch_equity_history(self, limit: int | None = None) -> list[EquityPoint]:
        """``GET /account/equity-history`` — recent equity samples, oldest first.

        A 5s-cadence, ~1h window of account equity: the high-resolution recent
        view, where :meth:`fetch_portfolio_history` is the downsampled
        long-window one. Requires credentials.

        Returns the first page only. ``limit`` bounds it and must fall in
        ``1..720`` (:data:`EQUITY_HISTORY_LIMIT_MAX`). Unlike the other paginated
        endpoints, 720 is *also* the server's default here — the whole window fits
        in one page — so omitting ``limit`` asks for the maximum, and one page is
        usually the entire series. For a longer walk (or a resumable one) use
        :meth:`iter_equity_history` or :meth:`fetch_equity_history_page`.
        """
        return (await self.fetch_equity_history_page(limit=limit)).items

    async def fetch_equity_history_page(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[EquityPoint]:
        """``GET /account/equity-history`` — one page of samples, plus its cursor.

        The manual-paging form; see :meth:`fetch_trades_page`. Requires
        credentials.
        """
        query = _query(
            limit=_page_limit(limit, EQUITY_HISTORY_LIMIT_MAX, "account/equity-history"),
            cursor=cursor,
        )
        data, next_cursor = await self._request_page(
            "/account/equity-history", query=query, signed=True
        )
        rows = data if isinstance(data, list) else []
        return Page([EquityPoint.from_dict(p) for p in rows], next_cursor)

    def iter_equity_history(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[EquityPoint]:
        """Every available equity sample, paging by cursor as needed.

        A generator; each page costs one signed request, issued lazily. ``limit``
        sets the page size, ``cursor`` resumes from a saved position, and
        ``max_pages`` bounds the walk.

        See :mod:`nexus_exchange.pagination` for the termination rules.
        """
        _check_iter_args(limit, EQUITY_HISTORY_LIMIT_MAX, "account/equity-history", max_pages)
        return aiter_items(
            lambda c: self.fetch_equity_history_page(limit=limit, cursor=c),
            cursor=cursor,
            max_pages=max_pages,
        )

    async def fetch_my_trades(self, limit: int | None = None) -> list[Fill]:
        """``GET /fills`` — recent fills (private executions). Requires credentials.

        Returns the first page only. ``limit`` bounds it and must fall in
        ``1..1000`` (:data:`FILLS_LIMIT_MAX`); omit it for the server's default of
        100. For the full history use :meth:`iter_my_trades` (every fill) or
        :meth:`fetch_my_trades_page` (one page plus its cursor).
        """
        return (await self.fetch_my_trades_page(limit=limit)).items

    async def fetch_my_trades_page(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[Fill]:
        """``GET /fills`` — one page of fills, plus its next cursor.

        The manual-paging form; see :meth:`fetch_trades_page`. Requires
        credentials.
        """
        query = _query(
            limit=_page_limit(limit, FILLS_LIMIT_MAX, "fills"),
            cursor=cursor,
        )
        data, next_cursor = await self._request_page("/fills", query=query, signed=True)
        rows = data if isinstance(data, list) else []
        return Page([Fill.from_dict(f) for f in rows], next_cursor)

    def iter_my_trades(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[Fill]:
        """Every fill on the account, paging by cursor as needed.

        A generator; each page costs one signed request, issued lazily. ``limit``
        sets the page size, ``cursor`` resumes from a saved position, and
        ``max_pages`` bounds the walk. Requires credentials.

        See :mod:`nexus_exchange.pagination` for the termination rules.
        """
        _check_iter_args(limit, FILLS_LIMIT_MAX, "fills", max_pages)
        return aiter_items(
            lambda c: self.fetch_my_trades_page(limit=limit, cursor=c),
            cursor=cursor,
            max_pages=max_pages,
        )

    async def fetch_withdrawals(self) -> list[Withdrawal]:
        """``GET /withdrawals`` — withdrawal history. Requires credentials."""
        data = await self._request("GET", "/withdrawals", signed=True)
        return [Withdrawal.from_dict(w) for w in (data if isinstance(data, list) else [])]

    async def fetch_deposits(self, limit: int | None = None) -> list[FundsEntry]:
        """``GET /deposits`` — the account's funds ledger. Requires credentials.

        Despite the path, entries are not deposits only: each carries a ``kind``
        of ``deposit`` | ``withdrawal`` | ``faucet``, so this is the combined
        movements ledger. Filter on ``kind`` if you want one of them.

        Distinct from :meth:`fetch_bridge_deposits`, which tracks *cross-chain*
        deposits through the watcher and reports confirmation progress. This is
        the account-side ledger; that one is the bridge pipeline.

        ``limit`` maxes out at :data:`DEPOSITS_LIMIT_MAX`, which is also the
        server default.

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        limit = _page_limit(limit, DEPOSITS_LIMIT_MAX, "deposits")
        query = _query(limit=limit)
        data = await self._request("GET", "/deposits", query=query, signed=True)
        return [FundsEntry.from_dict(e) for e in (data if isinstance(data, list) else [])]

    async def fetch_funding_history(self, limit: int | None = None) -> list[AccountFunding]:
        """``GET /funding`` — funding payments for the account. Requires credentials.

        The account-side counterpart of :meth:`fetch_funding_rate_history`,
        which is a *market's* funding series and takes no credentials. Amounts
        are signed; prefer the sign over the redundant ``direction`` field.

        ``limit`` maxes out at :data:`ACCOUNT_FUNDING_LIMIT_MAX` (default 100).

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        limit = _page_limit(limit, ACCOUNT_FUNDING_LIMIT_MAX, "funding")
        query = _query(limit=limit)
        data = await self._request("GET", "/funding", query=query, signed=True)
        return [AccountFunding.from_dict(f) for f in (data if isinstance(data, list) else [])]

    # -- bridge (deposits) ---------------------------------------------------

    async def fetch_bridge_assets(self) -> BridgeAssetsResponse:
        """``GET /bridge/assets`` — bridgeable chains and assets. No credentials needed.

        Public, like the other catalogue reads on this surface: the pinned spec
        declares ``security: []`` for this operation, and the answer is the same
        for every caller — which chains and assets the bridge accepts is not
        account-specific. It is the only read in the bridge group that is.

        It used to be sent HMAC-signed (ENG-13303), which made a keyless client
        raise :class:`MissingCredentialsError` before the transport and put the
        chain list — the input to :meth:`create_bridge_deposit_address` — out of
        reach of anyone who had not yet minted a key. Sending a signature the
        contract does not ask for bought nothing and cost that.
        """
        data = await self._request("GET", "/api/v1/bridge/assets")
        return BridgeAssetsResponse.from_dict(data if isinstance(data, dict) else {})

    async def create_bridge_deposit_address(self, chain: str) -> BridgeDepositAddress:
        """``POST /bridge/deposit-addresses`` — get-or-create the account's deposit
        address on ``chain`` (idempotent per account+chain). Requires credentials.

        .. deprecated:: Nothing serves this route: it left the contract with
           ENG-10373 and its design was cancelled with ENG-11460, so every call
           fails. It will be removed in a later minor release.
        """
        warnings.warn(
            "`create_bridge_deposit_address` is deprecated: no server implements "
            "POST /bridge/deposit-addresses (ENG-11460). "
            "It will be removed in a later minor release.",
            DeprecationWarning,
            stacklevel=2,
        )
        data = await self._request(
            "POST",
            "/api/v1/bridge/deposit-addresses",
            body={"chain": chain},
            signed=True,
        )
        return BridgeDepositAddress.from_dict(data if isinstance(data, dict) else {})

    async def fetch_bridge_deposit_addresses(self) -> list[BridgeDepositAddress]:
        """``GET /bridge/deposit-addresses`` — list deposit addresses. Requires credentials.

        .. deprecated:: Nothing serves this route: it left the contract with
           ENG-10373 and its design was cancelled with ENG-11460, so every call
           fails. It will be removed in a later minor release. The old name
           ``list_bridge_deposit_addresses`` is the same method and warns the same
           way.
        """
        warnings.warn(
            "`fetch_bridge_deposit_addresses` (old name `list_bridge_deposit_addresses`) "
            "is deprecated: no server implements GET /bridge/deposit-addresses (ENG-11460). "
            "It will be removed in a later minor release.",
            DeprecationWarning,
            stacklevel=2,
        )
        data = await self._request("GET", "/api/v1/bridge/deposit-addresses", signed=True)
        return [BridgeDepositAddress.from_dict(a) for a in (data if isinstance(data, list) else [])]

    async def fetch_bridge_deposits(
        self,
        limit: int | None = None,
        chain: str | None = None,
        asset: str | None = None,
        status: str | None = None,
    ) -> list[BridgeDeposit]:
        """``GET /bridge/deposits`` — the account's bridge deposits; all filters
        optional. Poll a deposit until its ``status`` reaches ``credited``.
        Requires credentials.
        """
        query = _query(limit=limit, chain=chain, asset=asset, status=status)
        data = await self._request("GET", "/api/v1/bridge/deposits", query=query, signed=True)
        return [BridgeDeposit.from_dict(x) for x in (data if isinstance(data, list) else [])]

    async def fetch_bridge_deposit(self, deposit_id: str) -> BridgeDeposit:
        """``GET /bridge/deposits/{id}`` — a single bridge deposit. Requires credentials."""
        data = await self._request(
            "GET",
            f"/api/v1/bridge/deposits/{quote(deposit_id, safe='')}",
            signed=True,
        )
        return BridgeDeposit.from_dict(data if isinstance(data, dict) else {})

    async def fetch_rate_limit_status(self) -> RateLimitStatus:
        """``GET /account/rate-limit`` — the caller's rate-limit status.

        Requires credentials. Does not consume a rate-limit token.
        """
        data = await self._request("GET", "/account/rate-limit", signed=True)
        return RateLimitStatus.from_dict(data if isinstance(data, dict) else {})

    async def fetch_cancel_on_disconnect(self) -> CancelOnDisconnectStatus:
        """``GET /account/cancel-on-disconnect`` — the account's COD state.

        Requires credentials. ``enabled`` is the account's own opt-in, while
        ``active`` is whether COD will actually fire (the opt-in *and* the
        exchange-side feature switch): ``enabled`` true with ``active`` false
        means the exchange has the feature switched off.
        """
        data = await self._request("GET", "/account/cancel-on-disconnect", signed=True)
        return CancelOnDisconnectStatus.from_dict(data if isinstance(data, dict) else {})

    # -- account (signed writes) -----------------------------------------
    async def deposit(self, amount: Decimal | str) -> DepositResult:
        """``POST /account/deposit`` — deposit USDX collateral. Requires credentials.

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        data = await self._request(
            "POST", "/account/deposit", body={"amount": str(amount)}, signed=True
        )
        return DepositResult.from_dict(data if isinstance(data, dict) else {})

    async def claim_credit(self, amount: Decimal | str | None = None) -> CreditResult:
        """``POST /account/credit`` — claim synthetic (testnet) USDX from the faucet.

        Omit ``amount`` to claim the full remaining daily allowance. Requires
        credentials.

        Testnet and local only — the spec marks this operation
        ``x-nexus-network-availability: [testnet, local]``, and mainnet has no
        faucet because its collateral is USDX bridged from Ethereum Mainnet.
        Raises :class:`ValueError` on a faucet-less network rather than spending
        a signed request against a real-funds host.
        """
        if not self._network.has_faucet:
            raise ValueError(
                f"{self._network.label} has no faucet: `claim_credit` mints synthetic "
                f"funds and is testnet/local only. Real collateral is bridged — see "
                f"`deposit`."
            )
        body = {} if amount is None else {"amount": str(amount)}
        data = await self._request("POST", "/account/credit", body=body, signed=True)
        return CreditResult.from_dict(data if isinstance(data, dict) else {})

    async def create_deposit(
        self, amount: Decimal | str, asset: str | None = None
    ) -> DepositResponse:
        """``POST /deposits`` — submit a (testnet/synthetic) deposit. Requires credentials.

        Distinct from :meth:`deposit` (``POST /account/deposit``, "deposit USDX
        collateral"): the spec declares them as two operations with two response
        schemas, and this SDK wraps each at its own path rather than guessing
        that one supersedes the other.

        ``asset`` defaults to ``USDX`` server-side and is omitted from the body
        when not given, so the default is the server's rather than one this
        client invents and would have to track.

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        # `Decimal("abc")` raises `InvalidOperation`, an `ArithmeticError` rather
        # than a `ValueError`, so an unparseable amount would surface as a
        # decimal-internals error instead of the argument error it is. Catch it
        # and re-raise in the same shape as the range check below, so a caller
        # has one exception type to handle for "bad amount".
        try:
            parsed = Decimal(str(amount))
        except InvalidOperation as exc:
            raise ValueError(f"deposit amount must be a positive decimal (got {amount!r})") from exc
        # Rejects NaN and Infinity too: both are finite-looking to `> 0` in ways
        # that would put a nonsense amount on the wire.
        if not parsed.is_finite() or parsed <= 0:
            raise ValueError(f"deposit amount must be a positive decimal (got {amount!r})")
        body: dict[str, Any] = {"amount": str(amount)}
        if asset is not None:
            body["asset"] = asset
        data = await self._request("POST", "/deposits", body=body, signed=True)
        return DepositResponse.from_dict(data if isinstance(data, dict) else {})

    async def claim_faucet(self) -> FaucetResponse:
        """``POST /faucet`` — claim the fixed testnet faucet amount.

        Requires credentials. Takes no arguments: the amount is fixed by the
        server, subject to a per-wallet cooldown and a cumulative cap. A claim
        before the cooldown elapses returns ``429``; the response's
        ``available_at_ms`` is when the next one is due, so schedule against it
        rather than retrying blind.

        Distinct from :meth:`claim_credit` (``POST /account/credit``), which
        draws on a per-API-key *daily allowance* and takes an amount. Both mint
        synthetic USDX, and both are separate spec operations.

        Testnet and local only — the spec marks this operation
        ``x-nexus-network-availability: [testnet, local]``, the same marker
        ``POST /account/credit`` carries. Raises :class:`ValueError` on a
        faucet-less network rather than spending a signed request against a
        real-funds host.
        """
        if not self._network.has_faucet:
            raise ValueError(
                f"{self._network.label} has no faucet: `claim_faucet` mints synthetic "
                f"funds and is testnet/local only. Real collateral is bridged — see "
                f"`deposit`."
            )
        data = await self._request("POST", "/faucet", signed=True)
        return FaucetResponse.from_dict(data if isinstance(data, dict) else {})

    async def add_margin(
        self, market_id: str, direction: str, amount: Decimal | str
    ) -> MarginAdjustment:
        """``POST /account/margin`` — add/remove isolated margin on a position.

        Requires credentials. Only applies to a position in ``isolated`` margin
        mode; the server rejects a cross-margined position with
        ``MarginModeNotIsolated``. ``direction`` is ``"add"`` or ``"remove"``
        (sent verbatim); ``amount`` is the collateral to move, sent as a decimal
        string and must be positive.

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        if not market_id:
            raise ValueError("market_id is required")
        if direction not in ("add", "remove"):
            raise ValueError('direction must be "add" or "remove"')
        if Decimal(str(amount)) <= 0:
            raise ValueError("margin amount must be positive")
        data = await self._request(
            "POST",
            "/account/margin",
            body={"market_id": market_id, "direction": direction, "amount": str(amount)},
            signed=True,
        )
        return MarginAdjustment.from_dict(data if isinstance(data, dict) else {})

    async def set_cancel_on_disconnect(self, enabled: bool) -> CancelOnDisconnectStatus:
        """``PUT /account/cancel-on-disconnect`` — opt the account in/out of COD.

        Requires credentials. Returns the updated status; note the returned
        ``active`` may stay false even when ``enabled`` is true if the exchange
        has the feature switched off (see :meth:`fetch_cancel_on_disconnect`).
        """
        data = await self._request(
            "PUT",
            "/account/cancel-on-disconnect",
            body={"enabled": enabled},
            signed=True,
        )
        return CancelOnDisconnectStatus.from_dict(data if isinstance(data, dict) else {})

    # -- orders (signed) -------------------------------------------------
    async def create_order(self, order: OrderRequest) -> OrderResponse:
        """``POST /orders`` — place a single order. Requires credentials."""
        data = await self._request("POST", "/orders", body=order.to_payload(), signed=True)
        return OrderResponse.from_dict(data if isinstance(data, dict) else {})

    async def preview_order(self, order: OrderRequest) -> PreviewResponse:
        """``POST /orders/preview`` — project an order's impact without placing it.

        Requires credentials. Takes the same :class:`OrderRequest` as
        :meth:`create_order` and sends the identical body, so a preview and the
        order it previews cannot drift apart.

        **Nothing is submitted, and nothing is reserved.** The projection is
        against the book and the account as they are at the moment of the call;
        an ``accepted`` preview is not a promise that the subsequent
        :meth:`create_order` will be accepted, and the projected fill VWAP is
        not a quote. Treat it as a pre-trade check, not a two-phase commit.

        Counts against the ``trading`` rate-limit class (the spec marks it
        ``x-nexus-rate-limit-class: trading``), so previewing every candidate
        order spends the same budget placing them would.
        """
        data = await self._request("POST", "/orders/preview", body=order.to_payload(), signed=True)
        return PreviewResponse.from_dict(data if isinstance(data, dict) else {})

    async def create_orders(self, orders: list[OrderRequest]) -> list[BatchOrderResult]:
        """``POST /orders/batch`` — submit a batch of orders (sequential, non-atomic).

        Requires credentials. Returns one :class:`BatchOrderResult` per submitted
        order, in request order. The batch is non-atomic, so each entry
        independently reports either a placed order (``outcome == "ok"``) or a
        per-order rejection (``outcome == "err"``) — check ``result.is_ok`` /
        ``result.is_err`` on each entry.

        Positional alignment is preserved even for malformed payloads: a
        response element that is not an object decodes to an ``err``-shaped
        placeholder (``error == "malformed_result"``) rather than being
        dropped, and a payload that is not a list at all yields one such
        placeholder per submitted order — so ``zip(orders, results)`` is
        always safe.
        """
        body = [o.to_payload() for o in orders]
        data = await self._request("POST", "/orders/batch", body=body, signed=True)
        if not isinstance(data, list):
            # A non-list payload carries no per-order results to align; surface
            # one error-shaped entry per submitted order instead of returning [].
            return [BatchOrderResult.malformed(data) for _ in orders]
        return [
            BatchOrderResult.from_dict(r) if isinstance(r, dict) else BatchOrderResult.malformed(r)
            for r in data
        ]

    async def fetch_open_orders(self) -> list[Order]:
        """``GET /orders`` — open orders for the account. Requires credentials."""
        data = await self._request("GET", "/orders", signed=True)
        return [Order.from_dict(o) for o in (data if isinstance(data, list) else [])]

    async def fetch_orders(self, limit: int | None = None) -> list[OrderHistoryEntry]:
        """``GET /orders/history`` — terminal-status orders, newest first.

        Filled / cancelled / rejected / expired orders for the account, the
        history counterpart of :meth:`fetch_open_orders`. Requires credentials.

        Returns the first page only. ``limit`` bounds it and must fall in
        ``1..500`` (:data:`ORDER_HISTORY_LIMIT_MAX` — lower than the 1000 fills
        and trades allow); omit it for the server's default of 100. For the whole
        history use :meth:`iter_orders`, or
        :meth:`fetch_orders_page` for one page plus its cursor.
        """
        return (await self.fetch_orders_page(limit=limit)).items

    async def fetch_orders_page(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Page[OrderHistoryEntry]:
        """``GET /orders/history`` — one page of order history, plus its next cursor.

        The manual-paging form; see :meth:`fetch_trades_page`. Requires
        credentials.
        """
        query = _query(
            limit=_page_limit(limit, ORDER_HISTORY_LIMIT_MAX, "orders/history"),
            cursor=cursor,
        )
        data, next_cursor = await self._request_page("/orders/history", query=query, signed=True)
        rows = data if isinstance(data, list) else []
        return Page([OrderHistoryEntry.from_dict(o) for o in rows], next_cursor)

    def iter_orders(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[OrderHistoryEntry]:
        """Every terminal-status order on the account, paging by cursor as needed.

        A generator; each page costs one signed request, issued lazily. ``limit``
        sets the page size, ``cursor`` resumes from a saved position, and
        ``max_pages`` bounds the walk — worth setting on an account with a long
        trading history, since nothing else limits how far back this goes.

        See :mod:`nexus_exchange.pagination` for the termination rules.
        """
        _check_iter_args(limit, ORDER_HISTORY_LIMIT_MAX, "orders/history", max_pages)
        return aiter_items(
            lambda c: self.fetch_orders_page(limit=limit, cursor=c),
            cursor=cursor,
            max_pages=max_pages,
        )

    async def fetch_order(self, order_id: str, market_id: str) -> Order:
        """``GET /orders/{order_id}`` — fetch a single order. Requires credentials.

        ``market_id`` is required: the engine routes single-order operations to
        the owning market (ENG-3123) and its extractor rejects a request without
        ``?market_id=`` before any handler runs, so the call could never succeed
        without it (ENG-17118). It is sent as a query parameter, so it is part of
        the signed canonical string. An empty value raises :class:`ValueError`
        before any request.

        Requested at the unprefixed path because that is the operation the pinned
        spec defines: ``GET /api/v1/orders/{order_id}`` exists on the monorepo's
        spec but in no published release yet, and the SDK implements only what
        the pinned spec defines (ENG-8616). The indexer serves this route at both
        mounts (ENG-5298), and the unprefixed one resolves against
        :attr:`base_url` — on every published network the same host as the
        ``/api/v1`` surface, not the retired ``/api/exchange`` gateway.
        """
        if not market_id:
            raise ValueError("market_id is required")
        query = urlencode({"market_id": market_id})
        data = await self._request(
            "GET", f"/orders/{quote(order_id, safe='')}", query=query, signed=True
        )
        return Order.from_dict(data if isinstance(data, dict) else {})

    async def cancel_order(self, order_id: str, market_id: str) -> Any:
        """``DELETE /orders/{order_id}`` — cancel a single order. Requires credentials.

        ``market_id`` is required (the engine routes the cancel by market,
        ENG-3123; a request without it is rejected, ENG-17118) and is sent as a
        query parameter, so it is part of the signed canonical string. An empty
        value raises :class:`ValueError` before any request.
        """
        if not market_id:
            raise ValueError("market_id is required")
        query = urlencode({"market_id": market_id})
        return await self._request(
            "DELETE",
            f"/orders/{quote(order_id, safe='')}",
            query=query,
            signed=True,
        )

    async def cancel_all_orders(self) -> Any:
        """``DELETE /orders`` — cancel all open orders. Requires credentials."""
        return await self._request("DELETE", "/orders", signed=True)

    async def edit_order(self, order_id: str, market_id: str, amend: AmendOrder) -> OrderResponse:
        """``PATCH /orders/{order_id}`` — amend a resting order's price/size.

        Requires credentials. ``market_id`` is required (the engine routes the
        amend by market, ENG-4645) and is sent as a query parameter, so it is
        part of the signed canonical string. ``amend`` must change at least one
        field; an empty amend raises :class:`ValueError` before any request.
        """
        if not market_id:
            raise ValueError("market_id is required")
        if not amend.has_changes():
            raise ValueError("edit_order requires at least one field to change")
        query = urlencode({"market_id": market_id})
        data = await self._request(
            "PATCH",
            f"/orders/{quote(order_id, safe='')}",
            query=query,
            body=amend.to_payload(),
            signed=True,
        )
        return OrderResponse.from_dict(data if isinstance(data, dict) else {})

    # -- keys / agents (signed) ------------------------------------------
    async def fetch_api_keys(self) -> list[ApiKeyInfo]:
        """``GET /keys`` — API keys for the session. Requires credentials."""
        data = await self._request("GET", "/keys", signed=True)
        return [ApiKeyInfo.from_dict(k) for k in (data if isinstance(data, list) else [])]

    async def create_api_key(self, session_token: str) -> ApiKeyCreated:
        """``POST /keys`` — mint a new HMAC API key for the authenticated wallet.

        The spec declares three operations under ``bearerAuth`` — this one,
        ``GET /keys`` and ``DELETE /keys/{key_id}`` — but this is the only one
        that *cannot* be HMAC-signed: it is what you call to *obtain* HMAC
        credentials, so it cannot require them. The other two this client sends
        signed (:meth:`fetch_api_keys`, :meth:`delete_api_key`); which side is
        authoritative there is ENG-13303, so do not align them onto either
        scheme by reading this method as the pattern. Get
        ``session_token`` from :meth:`login` (:attr:`LoginResponse.token`);
        this SDK does not store it, so pass it in explicitly. This client's own
        ``api_key``/``api_secret`` are not used and need not be set.

        **The secret comes back once and is never recoverable.** Persist it at
        the call site — see :class:`~nexus_exchange.ApiKeyCreated`, whose
        ``repr`` redacts it so an incidental log cannot leak a live credential.

        **The key is bound to the network of the host that mints it.** There is
        no network field either way, and another host refuses the key with an
        opaque ``401`` indistinguishable from an unknown one. This client's
        target decides: mint against the host you intend to trade on
        (:attr:`base_url`), and mint a separate key per network rather than
        reusing one.

        Not in the ``/api/v1`` spec; stays on the legacy gateway.
        """
        token = _bearer_token(session_token)
        data = await self._request("POST", "/keys", bearer=token)
        return ApiKeyCreated.from_dict(data if isinstance(data, dict) else {})

    async def delete_api_key(self, key_id: str) -> Any:
        """``DELETE /keys/{key_id}`` — delete an API key you own. Requires credentials."""
        return await self._request("DELETE", f"/keys/{quote(key_id, safe='')}", signed=True)

    async def fetch_agents(self) -> list[AgentInfo]:
        """``GET /agents`` — non-expired agent keys. Requires HMAC credentials.

        Refused for an agent-key client (:class:`~nexus_exchange.AgentKeyRefusedError`):
        an agent key cannot manage agent credentials.
        """
        data = await self._request("GET", "/agents", signed=True)
        return [AgentInfo.from_dict(a) for a in (data if isinstance(data, list) else [])]

    async def revoke_agent(self, address: str) -> Any:
        """``DELETE /agents/{address}`` — revoke an agent key. Requires HMAC credentials.

        Refused for an agent-key client (:class:`~nexus_exchange.AgentKeyRefusedError`):
        an agent key cannot revoke itself or any other agent.
        """
        return await self._request("DELETE", f"/agents/{quote(address, safe='')}", signed=True)

    async def create_ws_token(self) -> WsToken:
        """``POST /ws/token`` — mint a single-use WebSocket token. Requires credentials.

        Accepts HMAC keys, registered agent keys and session tokens, and the
        token it returns encodes the account identity, so the per-account
        channels (orders, fills, positions, balances, liquidations) scope
        themselves to the connected wallet.

        The token is short-lived (60s) and single-use. Pass it as ``?token=...``
        when upgrading to ``GET /ws``, and mint a fresh one per connection.
        :class:`~nexus_exchange.ws.WsClient` does both for you: pass
        ``token_provider=lambda: client.create_ws_token().token`` and it re-mints
        on every (re)connect. With :class:`~nexus_exchange.AsyncClient`, pass an
        ``async def`` that returns ``(await client.create_ws_token()).token``
        instead: ``WsClient`` awaits a coroutine function, and runs anything else
        in a worker thread.
        """
        data = await self._request("POST", "/ws/token", signed=True)
        return WsToken.from_dict(data if isinstance(data, dict) else {})

    # -- admin (signed) --------------------------------------------------
    # Admin/observability was intentionally excluded from the /api/v1 spec
    # (ENG-4748), so these stay on the legacy gateway.
    async def set_tier(self, address: str, tier: str) -> TierOverride:
        """``PUT /admin/tiers`` — set an account's rate-limit tier. Requires admin creds."""
        data = await self._request(
            "PUT", "/admin/tiers", body={"address": address, "tier": tier}, signed=True
        )
        return TierOverride.from_dict(data if isinstance(data, dict) else {})

    async def fetch_tiers(self) -> list[TierOverride]:
        """``GET /admin/tiers`` — list tier overrides. Requires admin creds."""
        data = await self._request("GET", "/admin/tiers", signed=True)
        return [TierOverride.from_dict(t) for t in (data if isinstance(data, list) else [])]

    async def delete_tier(self, address: str) -> Any:
        """``DELETE /admin/tiers/{address}`` — reset to default tier. Requires admin creds."""
        return await self._request("DELETE", f"/admin/tiers/{quote(address, safe='')}", signed=True)

    # -- deprecated aliases (R2.25, ENG-17744) ----------------------------
    # Each method was renamed to ``snake_case(operationId)`` of the operation it
    # calls. The old names delegate and warn for one minor release, then go.
    async def fetch_market_summaries(self) -> list[MarketSummary]:
        """Deprecated alias for :meth:`fetch_markets_summary`."""
        _warn_renamed("fetch_market_summaries", "fetch_markets_summary")
        return await self.fetch_markets_summary()

    async def fetch_market_adl_events(
        self, market_id: str, limit: int | None = None
    ) -> list[AdlEvent]:
        """Deprecated alias for :meth:`fetch_adl_events`."""
        _warn_renamed("fetch_market_adl_events", "fetch_adl_events")
        return await self.fetch_adl_events(market_id, limit)

    async def fetch_account_adl_history(
        self, address: str, limit: int | None = None
    ) -> list[AdlEvent]:
        """Deprecated alias for :meth:`fetch_adl_history`."""
        _warn_renamed("fetch_account_adl_history", "fetch_adl_history")
        return await self.fetch_adl_history(address, limit)

    async def fetch_service_health(self) -> ServiceHealth:
        """Deprecated alias for :meth:`fetch_status`."""
        _warn_renamed("fetch_service_health", "fetch_status")
        return await self.fetch_status()

    async def sign_in(self, signer: EthSigner) -> LoginResponse:
        """Deprecated alias for :meth:`login`."""
        _warn_renamed("sign_in", "login")
        return await self.login(signer)

    async def fetch_closed_positions(self, limit: int | None = None) -> list[ClosedPosition]:
        """Deprecated alias for :meth:`fetch_positions_history`."""
        _warn_renamed("fetch_closed_positions", "fetch_positions_history")
        return await self.fetch_positions_history(limit)

    async def fetch_closed_positions_page(
        self, *, limit: int | None = None, cursor: str | None = None
    ) -> Page[ClosedPosition]:
        """Deprecated alias for :meth:`fetch_positions_history_page`."""
        _warn_renamed("fetch_closed_positions_page", "fetch_positions_history_page")
        return await self.fetch_positions_history_page(limit=limit, cursor=cursor)

    def iter_closed_positions(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[ClosedPosition]:
        """Deprecated alias for :meth:`iter_positions_history`."""
        _warn_renamed("iter_closed_positions", "iter_positions_history")
        return self.iter_positions_history(limit=limit, cursor=cursor, max_pages=max_pages)

    async def fetch_account_fees(self) -> AccountFees:
        """Deprecated alias for :meth:`fetch_trading_fees`."""
        _warn_renamed("fetch_account_fees", "fetch_trading_fees")
        return await self.fetch_trading_fees()

    async def fetch_account_funding(self, limit: int | None = None) -> list[AccountFunding]:
        """Deprecated alias for :meth:`fetch_funding_history`."""
        _warn_renamed("fetch_account_funding", "fetch_funding_history")
        return await self.fetch_funding_history(limit)

    async def adjust_margin(
        self, market_id: str, direction: str, amount: Decimal | str
    ) -> MarginAdjustment:
        """Deprecated alias for :meth:`add_margin`."""
        _warn_renamed("adjust_margin", "add_margin")
        return await self.add_margin(market_id, direction, amount)

    async def fetch_order_history(self, limit: int | None = None) -> list[OrderHistoryEntry]:
        """Deprecated alias for :meth:`fetch_orders`."""
        _warn_renamed("fetch_order_history", "fetch_orders")
        return await self.fetch_orders(limit)

    async def fetch_order_history_page(
        self, *, limit: int | None = None, cursor: str | None = None
    ) -> Page[OrderHistoryEntry]:
        """Deprecated alias for :meth:`fetch_orders_page`."""
        _warn_renamed("fetch_order_history_page", "fetch_orders_page")
        return await self.fetch_orders_page(limit=limit, cursor=cursor)

    def iter_order_history(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        max_pages: int | None = None,
    ) -> AsyncIterator[OrderHistoryEntry]:
        """Deprecated alias for :meth:`iter_orders`."""
        _warn_renamed("iter_order_history", "iter_orders")
        return self.iter_orders(limit=limit, cursor=cursor, max_pages=max_pages)

    async def amend_order(self, order_id: str, market_id: str, amend: AmendOrder) -> OrderResponse:
        """Deprecated alias for :meth:`edit_order`."""
        _warn_renamed("amend_order", "edit_order")
        return await self.edit_order(order_id, market_id, amend)

    async def set_account_tier(self, address: str, tier: str) -> TierOverride:
        """Deprecated alias for :meth:`set_tier`."""
        _warn_renamed("set_account_tier", "set_tier")
        return await self.set_tier(address, tier)

    async def fetch_tier_overrides(self) -> list[TierOverride]:
        """Deprecated alias for :meth:`fetch_tiers`."""
        _warn_renamed("fetch_tier_overrides", "fetch_tiers")
        return await self.fetch_tiers()

    async def reset_account_tier(self, address: str) -> Any:
        """Deprecated alias for :meth:`delete_tier`."""
        _warn_renamed("reset_account_tier", "delete_tier")
        return await self.delete_tier(address)

    # The old name is the same function, not a delegating wrapper: the route is
    # unserved (ENG-18023), so the one warning fetch_bridge_deposit_addresses
    # emits covers both names, and a wrapper would warn twice.
    list_bridge_deposit_addresses = fetch_bridge_deposit_addresses
