#!/usr/bin/env python3
"""Generate ``src/nexus_exchange/async_client.py`` from the sync ``Client`` (ENG-20361).

``AsyncClient`` has exactly ``Client``'s endpoint methods, so it is not written by
hand: this script copies every public method of ``Client`` and makes the I/O
awaitable. Request building, signing, retries and the error mapping are shared
code (``_ClientCore``), so the only thing generated is the thin per-endpoint
layer. The transform is mechanical and driven by the AST, not by regexes:

* each endpoint method becomes ``async def``, except ``iter_*``, which stay plain
  ``def`` and return an ``AsyncIterator`` built by ``aiter_items``;
* every call to ``self._request`` / ``self._request_page`` / another endpoint
  method gets an ``await`` (parenthesised when an attribute is read off the
  result, as in ``(await self.fetch_trades_page(...)).items``), except inside a
  ``lambda``: the pagination lambdas hand their coroutine to ``aiter_items``,
  which awaits it.

Run after changing ``Client``::

    python scripts/gen_async_client.py          # rewrite async_client.py
    python scripts/gen_async_client.py --check  # exit 1 if it is stale

``tests/test_async_client.py`` runs the same check, so a stale file fails CI.
The output is passed through ``ruff`` (import pruning/sorting and format), which
is why this needs the dev extra installed.
"""

from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PACKAGE = REPO / "src" / "nexus_exchange"
SOURCE = PACKAGE / "client.py"
TARGET = PACKAGE / "async_client.py"

#: The sync client's own I/O and lifecycle. Not copied: the async versions are
#: hand-written in ``_async_transport.py``.
_NOT_ENDPOINTS = frozenset({"close"})

#: Plumbing calls that become awaitable, in addition to the endpoint methods.
_ASYNC_PLUMBING = frozenset({"_request", "_request_page"})

HEADER = '''\
# GENERATED by scripts/gen_async_client.py from src/nexus_exchange/client.py.
# Do not edit by hand: change `Client`, then run `python scripts/gen_async_client.py`.
# tests/test_async_client.py fails while this file is stale.
"""Asynchronous HTTP client for the Nexus Exchange API.

:class:`AsyncClient` is :class:`~nexus_exchange.Client` with awaitable I/O over
``httpx.AsyncClient``. Every method, argument and docstring below is the sync
client's; see ``scripts/gen_async_client.py`` for how it is derived.
"""

from __future__ import annotations

'''

CLASS = '''

__all__ = ["AsyncClient"]


class AsyncClient(_AsyncTransport):
    """Async client for the Nexus Exchange REST API.

    The same surface as :class:`~nexus_exchange.Client`: the same constructor
    arguments (``http_client`` takes an ``httpx.AsyncClient``), the same
    methods, the same signing, retry policy and errors. Each method is a
    coroutine, except the ``iter_*`` walkers, which return an async iterator::

        async with AsyncClient() as client:
            markets = await client.fetch_markets()
            async for fill in client.iter_my_trades(limit=500):
                ...

    Retries back off with ``asyncio.sleep``, so they never block the event
    loop. Close with ``async with`` or :meth:`aclose`.

    The method docstrings are copied from :class:`~nexus_exchange.Client`, so
    where one says "generator" read "async iterator", and add the missing
    ``await`` to its examples.
    """
'''


def _line_offsets(data: bytes) -> list[int]:
    offsets = [0]
    for i, b in enumerate(data):
        if b == 0x0A:
            offsets.append(i + 1)
    return offsets


def render() -> str:
    """The expected contents of ``async_client.py``."""
    data = SOURCE.read_bytes()
    tree = ast.parse(data, str(SOURCE))
    starts = _line_offsets(data)

    def off(lineno: int, col: int) -> int:
        # ast columns are UTF-8 byte offsets, hence working on bytes throughout.
        return starts[lineno - 1] + col

    client = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Client")

    def is_endpoint(node: ast.stmt) -> bool:
        if isinstance(node, ast.FunctionDef):
            return (
                not node.name.startswith("_")
                and node.name not in _NOT_ENDPOINTS
                and not node.decorator_list
            )
        # `old_name = new_name` aliases between endpoints.
        return (
            isinstance(node, ast.Assign)
            and isinstance(node.value, ast.Name)
            and not node.value.id.startswith("_")
        )

    body = client.body
    first = next(i for i, n in enumerate(body) if is_endpoint(n))
    last = max(i for i, n in enumerate(body) if is_endpoint(n))
    stray = [n for n in body[first : last + 1] if not is_endpoint(n)]
    if stray:
        names = ", ".join(getattr(n, "name", type(n).__name__) for n in stray)
        raise SystemExit(
            f"Client's endpoint methods must be contiguous; move these out of the "
            f"endpoint block (or teach this generator about them): {names}"
        )
    endpoints = body[first : last + 1]

    # Copy from just after the preceding member, so section comments come along.
    start = off(body[first - 1].end_lineno + 1, 0)  # type: ignore[operator]
    end = off(body[last].end_lineno, body[last].end_col_offset)  # type: ignore[arg-type]

    awaitable = _ASYNC_PLUMBING | {
        n.name
        for n in endpoints
        if isinstance(n, ast.FunctionDef) and not n.name.startswith("iter_")
    }

    edits: list[tuple[int, int, str]] = []  # (offset, length to replace, text)
    parents: dict[ast.AST, ast.AST] = {}
    for node in endpoints:
        for parent in ast.walk(node):
            for child in ast.iter_child_nodes(parent):
                parents[child] = parent

    def in_lambda(node: ast.AST) -> bool:
        while node in parents:
            node = parents[node]
            if isinstance(node, ast.Lambda):
                return True
        return False

    for node in endpoints:
        if isinstance(node, ast.FunctionDef):
            if node.name.startswith("iter_"):
                ret = node.returns
                if not (
                    isinstance(ret, ast.Subscript)
                    and isinstance(ret.value, ast.Name)
                    and ret.value.id == "Iterator"
                ):
                    raise SystemExit(f"{node.name}: expected an `Iterator[...]` return type")
                edits.append(
                    (off(ret.value.lineno, ret.value.col_offset), len("Iterator"), "AsyncIterator")
                )
            else:
                edits.append((off(node.lineno, node.col_offset), 0, "async "))
        for sub in ast.walk(node):
            if not isinstance(sub, ast.Call):
                continue
            func = sub.func
            if isinstance(func, ast.Name) and func.id == "iter_items":
                edits.append((off(func.lineno, func.col_offset), len("iter_items"), "aiter_items"))
                continue
            if not (
                isinstance(func, ast.Attribute)
                and isinstance(func.value, ast.Name)
                and func.value.id == "self"
                and func.attr in awaitable
            ):
                continue
            if in_lambda(sub):
                continue
            begin = off(sub.lineno, sub.col_offset)
            if isinstance(parents.get(sub), ast.Attribute):
                edits.append((begin, 0, "(await "))
                edits.append((off(sub.end_lineno, sub.end_col_offset), 0, ")"))  # type: ignore[arg-type]
            else:
                edits.append((begin, 0, "await "))

    chunk = bytearray(data[start:end])
    for at, length, text in sorted(edits, key=lambda e: e[0], reverse=True):
        rel = at - start
        chunk[rel : rel + length] = text.encode()

    # Imports: everything client.py imports, plus the module-level helpers it
    # defines that the copied methods use. `ruff` prunes what goes unused.
    imports = [
        ast.get_source_segment(data.decode(), n)
        for n in tree.body
        if isinstance(n, (ast.Import, ast.ImportFrom))
        and not (isinstance(n, ast.ImportFrom) and n.module == "__future__")
    ]
    defined: set[str] = set()
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.ClassDef)):
            defined.add(n.name)
        elif isinstance(n, ast.Assign):
            defined.update(t.id for t in n.targets if isinstance(t, ast.Name))
        elif isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name):
            defined.add(n.target.id)
    used = {n.id for e in endpoints for n in ast.walk(e) if isinstance(n, ast.Name)}
    from_client = sorted(defined & used - {"Client"})

    text = (
        HEADER
        + "\n".join(s for s in imports if s)
        + "\nfrom collections.abc import AsyncIterator\n"
        + "from ._async_transport import _AsyncTransport\n"
        + "from .pagination import aiter_items\n"
        + f"from .client import ({', '.join(from_client)})\n"
        + CLASS
        + "\n"
        + chunk.decode()
        + "\n"
    )
    return _ruff(text)


def _ruff(text: str) -> str:
    def run(*args: str, source: str) -> str:
        proc = subprocess.run(
            [sys.executable, "-m", "ruff", *args, "--stdin-filename", str(TARGET), "-"],
            input=source,
            capture_output=True,
            text=True,
            cwd=REPO,
        )
        if proc.returncode != 0:
            raise SystemExit(f"ruff {' '.join(args)} failed:\n{proc.stderr}{proc.stdout}")
        return proc.stdout

    text = run("check", "--fix", "--select", "I,F401", "--quiet", source=text)
    return run("format", "--quiet", source=text)


def main() -> int:
    expected = render()
    if "--check" in sys.argv[1:]:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != expected:
            print(
                f"{TARGET.relative_to(REPO)} is stale: run `python scripts/gen_async_client.py`",
                file=sys.stderr,
            )
            return 1
        return 0
    TARGET.write_text(expected)
    print(f"wrote {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
